// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiY2mmTtIGzWTOOflXJgBoQPTjZs9GfY0',
    appId: '1:836911324936:web:14366a57e08a220faa96bd',
    messagingSenderId: '836911324936',
    projectId: 'vybgo-c2ee0',
    authDomain: 'vybgo-c2ee0.firebaseapp.com',
    storageBucket: 'vybgo-c2ee0.firebasestorage.app',
    measurementId: 'G-30ZWZQ0T4R',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA45ehF377IG9jfC6npxkDIggU7I_LzQE',
    appId: '1:836911324936:ios:670e670ff7ad3eb4aa96bd',
    messagingSenderId: '836911324936',
    projectId: 'vybgo-c2ee0',
    storageBucket: 'vybgo-c2ee0.firebasestorage.app',
    iosClientId: '836911324936-4sjcq1hqmskuospsdc22ddkjl398g821.apps.googleusercontent.com',
    iosBundleId: 'com.example.vybgo',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiQ6owAzZuCKMMBMHeiTCiu5X-HCfAkiA',
    appId: '1:836911324936:android:352463d3ec285591aa96bd',
    messagingSenderId: '836911324936',
    projectId: 'vybgo-c2ee0',
    storageBucket: 'vybgo-c2ee0.firebasestorage.app',
  );

}